<?php

return [

    'Andhra Pradesh' => [
        'Visakhapatnam',
        'Vijayawada',
        'Guntur',
        'Tirupati',
        'Nellore',
        'Kurnool',
        'Rajahmundry',
        'Kakinada',
        'Kadapa',
        'Anantapur',
        'Eluru',
        'Ongole',
        'Srikakulam',
        'Vizianagaram',
        'Machilipatnam',
    ],

    'Arunachal Pradesh' => [
        'Itanagar',
        'Naharlagun',
        'Tawang',
        'Pasighat',
        'Ziro',
        'Bomdila',
        'Along',
        'Tezu',
        'Namsai',
    ],

    'Assam' => [
        'Guwahati',
        'Dibrugarh',
        'Silchar',
        'Jorhat',
        'Nagaon',
        'Tinsukia',
        'Tezpur',
        'Sivasagar',
        'Bongaigaon',
        'Dhubri',
    ],

    'Bihar' => [
        'Patna',
        'Gaya',
        'Muzaffarpur',
        'Bhagalpur',
        'Darbhanga',
        'Purnia',
        'Bihar Sharif',
        'Ara',
        'Begusarai',
        'Katihar',
        'Munger',
        'Chapra',
        'Samastipur',
    ],

    'Chhattisgarh' => [
        'Raipur',
        'Bhilai',
        'Bilaspur',
        'Korba',
        'Durg',
        'Rajnandgaon',
        'Jagdalpur',
        'Raigarh',
        'Ambikapur',
    ],

    'Goa' => [
        'Panaji',
        'Vasco da Gama',
        'Margao',
        'Mapusa',
        'Ponda',
        'Calangute',
    ],

    'Gujarat' => [
        'Ahmedabad',
        'Surat',
        'Vadodara',
        'Rajkot',
        'Gandhinagar',
        'Bhavnagar',
        'Jamnagar',
        'Junagadh',
        'Anand',
        'Nadiad',
        'Bharuch',
        'Vapi',
        'Navsari',
        'Mehsana',
        'Morbi',
        'Gandhidham',
    ],

    'Haryana' => [
        'Gurugram',
        'Faridabad',
        'Panipat',
        'Ambala',
        'Hisar',
        'Karnal',
        'Rohtak',
        'Sonipat',
        'Yamunanagar',
        'Panchkula',
        'Bhiwani',
        'Rewari',
    ],

    'Himachal Pradesh' => [
        'Shimla',
        'Dharamshala',
        'Solan',
        'Mandi',
        'Baddi',
        'Kullu',
        'Manali',
        'Hamirpur',
        'Una',
    ],

    'Jharkhand' => [
        'Ranchi',
        'Jamshedpur',
        'Dhanbad',
        'Bokaro',
        'Deoghar',
        'Hazaribagh',
        'Giridih',
        'Ramgarh',
        'Chaibasa',
    ],

    'Karnataka' => [
        'Bangalore',
        'Mysore',
        'Mangalore',
        'Hubli',
        'Dharwad',
        'Belgaum',
        'Davangere',
        'Ballari',
        'Shivamogga',
        'Tumkur',
        'Udupi',
        'Hassan',
        'Mandya',
        'Raichur',
        'Kalaburagi',
        'Bidar',
        'Belagavi',
    ],

    'Kerala' => [
        'Thiruvananthapuram',
        'Kochi',
        'Kozhikode',
        'Thrissur',
        'Kollam',
        'Kannur',
        'Alappuzha',
        'Kottayam',
        'Palakkad',
        'Malappuram',
        'Kasaragod',
    ],

    'Madhya Pradesh' => [
        'Bhopal',
        'Indore',
        'Jabalpur',
        'Gwalior',
        'Ujjain',
        'Sagar',
        'Dewas',
        'Satna',
        'Ratlam',
        'Rewa',
        'Singrauli',
        'Burhanpur',
    ],

    'Maharashtra' => [
        'Mumbai',
        'Pune',
        'Nagpur',
        'Nashik',
        'Thane',
        'Aurangabad',
        'Navi Mumbai',
        'Solapur',
        'Kolhapur',
        'Amravati',
        'Nanded',
        'Sangli',
        'Jalgaon',
        'Akola',
        'Latur',
        'Ahmednagar',
        'Satara',
    ],

    'Manipur' => [
        'Imphal',
        'Thoubal',
        'Bishnupur',
        'Churachandpur',
        'Ukhrul',
    ],

    'Meghalaya' => [
        'Shillong',
        'Tura',
        'Jowai',
        'Nongpoh',
    ],

    'Mizoram' => [
        'Aizawl',
        'Lunglei',
        'Champhai',
        'Kolasib',
    ],

    'Nagaland' => [
        'Kohima',
        'Dimapur',
        'Mokokchung',
        'Tuensang',
        'Wokha',
    ],

    'Odisha' => [
        'Bhubaneswar',
        'Cuttack',
        'Rourkela',
        'Berhampur',
        'Sambalpur',
        'Puri',
        'Balasore',
        'Baripada',
        'Jharsuguda',
        'Angul',
    ],

    'Punjab' => [
        'Ludhiana',
        'Amritsar',
        'Jalandhar',
        'Patiala',
        'Bathinda',
        'Mohali',
        'Pathankot',
        'Hoshiarpur',
        'Moga',
        'Batala',
    ],

    'Rajasthan' => [
        'Jaipur',
        'Jodhpur',
        'Udaipur',
        'Kota',
        'Ajmer',
        'Bikaner',
        'Alwar',
        'Bharatpur',
        'Sikar',
        'Bhilwara',
        'Sri Ganganagar',
        'Beawar',
    ],

    'Sikkim' => [
        'Gangtok',
        'Namchi',
        'Gyalshing',
        'Mangan',
    ],

    'Tamil Nadu' => [
        'Chennai',
        'Coimbatore',
        'Madurai',
        'Tiruchirappalli',
        'Salem',
        'Tiruppur',
        'Erode',
        'Vellore',
        'Thoothukudi',
        'Tirunelveli',
        'Thanjavur',
        'Dindigul',
        'Hosur',
        'Nagercoil',
        'Kanchipuram',
    ],

    'Telangana' => [
        'Hyderabad',
        'Warangal',
        'Nizamabad',
        'Karimnagar',
        'Khammam',
        'Ramagundam',
        'Mahbubnagar',
        'Nalgonda',
        'Adilabad',
        'Siddipet',
        'Suryapet',
    ],

    'Tripura' => [
        'Agartala',
        'Dharmanagar',
        'Udaipur',
        'Kailasahar',
        'Ambassa',
    ],

    'Uttar Pradesh' => [
        'Lucknow',
        'Noida',
        'Greater Noida',
        'Ghaziabad',
        'Kanpur',
        'Agra',
        'Varanasi',
        'Prayagraj',
        'Meerut',
        'Bareilly',
        'Aligarh',
        'Moradabad',
        'Gorakhpur',
        'Mathura',
        'Ayodhya',
        'Saharanpur',
        'Jhansi',
        'Firozabad',
    ],

    'Uttarakhand' => [
        'Dehradun',
        'Haridwar',
        'Rishikesh',
        'Haldwani',
        'Roorkee',
        'Nainital',
        'Rudrapur',
        'Kashipur',
    ],

    'West Bengal' => [
        'Kolkata',
        'Howrah',
        'Durgapur',
        'Asansol',
        'Siliguri',
        'Kharagpur',
        'Haldia',
        'Bardhaman',
        'Malda',
        'Darjeeling',
    ],

    // Union Territories

    'Andaman and Nicobar Islands' => [
        'Port Blair',
        'Diglipur',
        'Havelock Island',
    ],

    'Chandigarh' => [
        'Chandigarh',
    ],

    'Dadra and Nagar Haveli and Daman and Diu' => [
        'Daman',
        'Diu',
        'Silvassa',
    ],

    'Delhi' => [
        'New Delhi',
        'Delhi',
    ],

    'Jammu and Kashmir' => [
        'Srinagar',
        'Jammu',
        'Anantnag',
        'Baramulla',
        'Kathua',
        'Udhampur',
    ],

    'Ladakh' => [
        'Leh',
        'Kargil',
    ],

    'Lakshadweep' => [
        'Kavaratti',
        'Agatti',
        'Amini',
    ],

    'Puducherry' => [
        'Puducherry',
        'Karaikal',
        'Mahe',
        'Yanam',
    ],

];